# Generated by Django 5.0.4 on 2024-04-21 09:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('images', models.ImageField(upload_to='media/03_BuyNotes')),
                ('file', models.FileField(upload_to='files/03_BuyNotes')),
                ('category', models.ManyToManyField(to='products.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
