# Generated by Django 5.0.4 on 2024-04-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='images',
            new_name='image',
        ),
    ]
