# Generated by Django 4.2.11 on 2024-04-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_images_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/03_BuyNotes'),
        ),
    ]
